name=eviltester.com
url=https://eviltester.com/
legalName=Compendium Developments Ltd
contactType=customer support
email=contact@eviltester.com
sameAs=https://www.youtube.com/@EvilTesterVideos,https://www.linkedin.com/in/eviltester/,https://github.com/eviltester,https://www.compendiumdev.co.uk